spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/dev/db/maxxyounglog
    username: sa
    password:
  jwt:
    secret: ${secret}
    token:
      access-expiration-time: ${access-expiration-time}
      refresh-expiration-time: ${refresh-expiration-time}