server:
  port: 8080

spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
kafka:
  bootstrap-servers: localhost:29092

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
domain: localhost
kafka:
  bootstrap-servers: localhost:29092
---
spring:
  config:
    activate:
      on-profile: stage
  jpa:
    hibernate:
      ddl-auto: update
domain: localhost
kafka:
  bootstrap-servers: localhost:9092
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
domain: localhost
kafka:
  bootstrap-servers: localhost:9092
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
domain: localhost